### ISSUE TITLE
[SUGGESTION] Features

### ISSUE THREAD

**Issue by ricardoprins** [Rishit-dagli/MakeCode-Android#10]
## :bulb: Do you have features planned for future development?
If yes, do you think it would be a good idea to have them here, so that others people (myself included) could work in some of these features? What is your opinion on that?

**Comment by Rishit-dagli** [comment]
@ricardoprins Yes! Certainly, I will add some of the features I am planning to work on, as issues. And everyone is more than welcome to create issues for the features. I will be actively adding labels to differentiate the features into beginners, experts, and so on. And then everyone could work on it, just leave a comment on the issue.

**Comment by ricardoprins** [comment]
That's great, I wanna help more with this project, but it would be great to know what's your vision for it!

**Comment by ricardoprins** [comment]
The answer to all questions is 42.

**Comment by Rishit-dagli** [comment]
@ricardoprins Currently I am working on two aspects-

1. UI - All UI concept additions are acceptable. I don't force any particular UI.
2. IoS - Since this app is built with [Kotlin](https://kotlinlang.org/) which does provide cross-platform capabilities, I am working on making this code IoS compatible too.

However, I am also open to hearing about any new concepts.

**Comment by ricardoprins** [comment]
Alright! I am tied up with three projects (btw, we need to plan out our next session), but once I'm done with one of them, I'll start working on this as well :)

**Comment by Rishit-dagli** [comment]
I am closing this issue as of now, let me know if you gave any more queries.
